web:
  image: sonarqube
  restart: always
  links:
   mysql: mysql
  ports:
   - "9000:9000"
  environment:
   SONARQUBE_JDBC_USERNAME: sonar
   SONARQUBE_JDBC_PASSWORD: sonar
   SONARQUBE_JDBC_URL: "jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8"
mysql:
  build: mysql
  restart: always
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root
  ports:
   - "3306:3306"
